### ISSUE TITLE
Implement predict.ergm.ego()

### ISSUE THREAD

**Issue by mbojan** [statnet/ergm.ego#46]
Implement `predict.ergm.ego()` which will compute predicted probabilities for the pseudo-population network.

**Comment by mbojan** [comment]
Need to fix statnet/ergm#172 first.

**Comment by mbojan** [comment]
Done.

**Comment by martinamorris** [comment]
Thank you!!!

**Comment by martinamorris** [comment]
Ok, still one problem, but i think we're 99% of the way there.

The offset in the first position is the ppop scaling adjustment.  in `ergm.ego`, theta(ppop adj) + theta(edges) = in `ergm` theta(edges).

So, we don't want to just delete that offset, we want to add it back to the edges theta first, then delete it.

Without this, the probabilities are not scaled correctly in the predict function:

```
> head(pnet)
   tail  head         p
1  3497  7317 0.6867611
2  7272  8277 0.7497954
3  7069 11762 0.4357120
4   435  8813 0.5929972
5  1275  8594 0.0000000
6 10672 10806 0.5315793
```

those probabilities should be much, much lower in this network with 15K nodes and 7K edges.

i'm tagging both @chad-klumb and @mbojan here, not sure who can get to it first.

**Comment by chad-klumb** [comment]
A possible alternative would be to use the `ergm.formula` rather than the `formula` attached to the `ergm.ego` object; then no removal or modification should be necessary.

**Comment by chad-klumb** [comment]
cf. PR #48 

you can `remotes::install_github("chad-klumb/ergm.ego@master")` to test (until it's merged)

**Comment by martinamorris** [comment]
thx for the quick response!  will try when i'm free (6:30ish)

**Comment by mbojan** [comment]
I was actually wondering if it should be in fact included...

We could also modify `ergmMPLE()` to return `foffset` element computed by `ergm.pl()` which is an already computed combined "effect" of the offset terms (sum of products of offset terms and their coefficients.

@chad-klumb , can you verify for a model with more than one offset term (plus net netsize adjustment) if the order of the parameter vector is the same as the columns of the "model matrix" (as returned by `ergmMPLE()`)? I recall that for some reason if `ergmMPLE()` was fed with `ergmegofit$ergm.formula` the netsize adjustment offset was moved from the first place in the formula.

I will be able to get back to it 8-10hrs.

**Comment by chad-klumb** [comment]
It looks like the problem is actually worse than that; it appears to move offsets (not just `netsize.adj`) to the last columns.

That will need to be changed or compensated for.

**Comment by mbojan** [comment]
Right. I did not manage yet to pin down why it happens. I think we need a reliable way of mapping formula terms to model matrix columns and to parameters. It will be invaluable in other contexts too.

All in all that means the problem affects ergm too, not only ergm.ego.

**Comment by chad-klumb** [comment]
The rearrangement happens here:

https://github.com/statnet/ergm/blob/38533f42b4e302f05e905145174bf105270f0cbc/R/predict.ergm.R#L103

**Comment by chad-klumb** [comment]
`nonsimp_update.formula` may be the solution

**Comment by chad-klumb** [comment]
With both `chad-klumb/ergm@master` and `chad-klumb/ergm.ego@master`, the following script

```
library(ergm.ego)
data("faux.magnolia.high")

fmhego <- as.egodata(faux.magnolia.high)

fit <- ergm.ego(fmhego ~ edges
                 + nodefactor("Grade")
                 + offset(nodemix("Grade", levels2=1))
                 + nodematch("Grade")
                 + offset(nodematch("Sex")),
                 offset.coef = c(-1,-2))

debug(predict)

pnet <- predict(fit)
```

shows that `predmat` is structured as

```
Browse[5]> head(predmat)
     tail head offset(netsize.adj) edges nodefactor.Grade.8 nodefactor.Grade.9 nodefactor.Grade.10 nodefactor.Grade.11 nodefactor.Grade.12 offset(mix.Grade.7.7) nodematch.Grade
[1,]  116  267                   1     1                  0                  1                   0                   1                   0                     0               0
[2,]   57 1433                   1     1                  0                  0                   0                   1                   1                     0               0
[3,]  610 1167                   1     1                  0                  0                   1                   0                   0                     0               0
[4,]   38  553                   1     1                  0                  1                   0                   0                   0                     0               0
[5,] 1043 1081                   1     1                  0                  0                   1                   1                   0                     0               0
[6,]  625 1317                   1     1                  1                  1                   0                   0                   0                     0               0
     offset(nodematch.Sex)
[1,]                     0
[2,]                     0
[3,]                     1
[4,]                     0
[5,]                     0
[6,]                     1
```

which I believe is the desired result, as

```
Browse[5]> fit$ergm.formula
popnw ~ offset(netsize.adj) + (edges + nodefactor("Grade") + 
    offset(nodemix("Grade", levels2 = 1)) + nodematch("Grade")) + 
    offset(nodematch("Sex"))
<environment: 0x000000000833e530>
Browse[5]> fit$coef
  offset(netsize.adj)                 edges    nodefactor.Grade.8    nodefactor.Grade.9   nodefactor.Grade.10   nodefactor.Grade.11   nodefactor.Grade.12 offset(mix.Grade.7.7) 
           -7.2868764             0.1513628            -0.3380101            -0.7668909            -0.6618398            -0.5076787            -0.5141862            -1.0000000 
      nodematch.Grade offset(nodematch.Sex) 
            3.4419170            -2.0000000 
```

**Comment by martinamorris** [comment]
aaaaaand.  we're back.  this time with a head-scratcher.  i believe @chad-klumb 's code is working fine.  and `predict()` without offsets is working fine.   and `predict()` with offsets respects the offsets (i.e., p(tie) for -Inf offset values is 0).

but offsets (esp. -Inf offsets) change the number of possible edges from the number of dyads to something less.  in the example below, no same-sex ties will be allowed.  this reduces the possible edges to 1/3 of the total dyads (only M-F, and undirected in this case. 

i don't think `predict` takes this into account when calculating the p(tie).   it does the right thing in terms of preventing same-sex ties.  but doesn't calculate the probability of a tie for the *possible* ties correctly.

reprex below

```
data("faux.magnolia.high")

# first without offsets

fit <- ergm(faux.magnolia.high ~ edges
                + nodefactor("Grade")
                + nodematch("Grade")
                + nodematch("Sex"))

pnet <- predict(fit) # data frame

vnet <- bind_rows(tibble(vertex.names=pnet[,1], p=pnet[,3]),
                  tibble(vertex.names=pnet[,2], p=pnet[,3]))

deg <- vnet %>%
  group_by(vertex.names) %>%
  summarize(deg = sum(p))

egos <- ergm.ego::as.egodata(faux.magnolia.high)$egos %>%
  mutate(vertex.names = as.numeric(vertex.names)) %>%
  right_join(deg)

## roughly equal:   stubs/2 = edges

sum(egos$deg)/2
summary(faux.magnolia.high ~ edges)

# now with offset - no samesex ties

fit <- ergm(faux.magnolia.high ~ edges
            + nodefactor("Grade")
            + nodematch("Grade")
            + offset(nodematch("Sex")),
            offset.coef = (-Inf))

pnet <- predict(fit) # data frame

vnet <- bind_rows(tibble(vertex.names=pnet[,1], p=pnet[,3]),
                  tibble(vertex.names=pnet[,2], p=pnet[,3]))

deg <- vnet %>%
  group_by(vertex.names) %>%
  summarize(deg = sum(p))

egos <- ergm.ego::as.egodata(faux.magnolia.high)$egos %>%
  mutate(vertex.names = as.numeric(vertex.names)) %>%
  right_join(deg)

## not even close:  stubs/2 != edges

sum(egos$deg)/2
summary(faux.magnolia.high ~ edges)

## let's look at the expected number of same and opp sex ties

pnet_sex <- fmhego$egos %>%
  select(vertex.names, Sex) %>%
  mutate(vertex.names = as.numeric(vertex.names)) %>%
  right_join(pnet, by = c("vertex.names" = "tail" )) %>%
  mutate(sex_tail = Sex) %>%
  select (-Sex)

pnet_sex <-  fmhego$egos %>%
  select(vertex.names, Sex) %>%
  mutate(vertex.names = as.numeric(vertex.names)) %>%
  right_join(pnet_sex, by = c("vertex.names" = "head" )) %>%
  mutate(sex_head = Sex) %>%
  select (-Sex)

## prediction respects offsets in p(tie) = 0 for samesex ties
## but p(tie) not adjusted accordingly for possible ties

pnet_sex %>%
  group_by(sex_tail, sex_head) %>%
  summarize(count = n(),
            pred = sum(p))

```

**Comment by chad-klumb** [comment]
`predict` shouldn't need to be adjusted to handle this

The problem is likely that the model is inconsistent with the data and only the MPLE is run by default since the model is dyad-independent.

```
> summary(faux.magnolia.high ~ nodemix("Sex"))
mix.Sex.F.F mix.Sex.F.M mix.Sex.M.M 
        430         285         259 
```

while with the offset

```
> sum(egos$deg)/2
[1] 267.1421
```
which is consistent.

Forcing the main method

```
fit <- ergm(faux.magnolia.high ~ edges
            + nodefactor("Grade")
            + nodematch("Grade")
            + offset(nodematch("Sex")),
            offset.coef = (-Inf),
            control=control.ergm(force.main=TRUE))

pnet <- predict(fit) # data frame

vnet <- bind_rows(tibble(vertex.names=pnet[,1], p=pnet[,3]),
                  tibble(vertex.names=pnet[,2], p=pnet[,3]))

deg <- vnet %>%
  group_by(vertex.names) %>%
  summarize(deg = sum(p))

egos <- ergm.ego::as.egodata(faux.magnolia.high)$egos %>%
  mutate(vertex.names = as.numeric(vertex.names)) %>%
  right_join(deg)

## not even close:  stubs/2 != edges

sum(egos$deg)/2
summary(faux.magnolia.high ~ edges)
```

also gives

```
> sum(egos$deg)/2
[1] 914.3843
> summary(faux.magnolia.high ~ edges)
edges 
  974 
```

which again is consistent.

**Comment by martinamorris** [comment]
thx @chad-klumb.  a couple of questions:

1.  offsets are often used in glms, and these are typically dyad-independent models that rely on the estimation algorithm we use for MPLE.   i thought that estimate was, in fact, the MLE in the glm setting.   so why doesn't the MPLE work properly?  shouldn't it still try to match the edge and nodefactor counts by redistributing the forbidden ties to allowed dyads?

2. i'm getting a similar result -- (sum(predicted edges) != sum(observed edges) -- in my predictions from my MCMLE ergm fits in the WHAMP context.  do i understand correctly from your comment above that the MCMLE fits should produce the right predicted degree?  if so, then i still have another problem to dx.

**Comment by chad-klumb** [comment]
`predict` may need to set maximum number of dyads or dyad types appropriately to ensure all dyads are represented in the result; this may explain your 2. if the return value from `predict` has fewer rows than your network's dyadcount; this would generally be an issue for larger networks (but has nothing to do with offsets)

dyads with infinite offset effects are omitted from the MPLE:

https://github.com/statnet/ergm/blob/8b00975987aac64f4009279a88aaf51305e40bdb/R/ergm.pl.R#L143-L148

**Comment by martinamorris** [comment]
Thx.  It looks like even in the faux.magnolia.high example, the total dyads returned by `predict()` is less than n choose 2.  Is that because predict maxes out at some fixed value?  The # returned dyads is 1,000,056, 1461 choose 2 = 1,066,530.  Maybe this explains why the sum(pred edge) < obs(edgecount).

And the number of dyads with n=15K (my WHAMP case) is much larger.

So, do we want to:

1. Sample from that huge space to get estimates of the predicted tie values.  My concern is that the space is large, and some of our subgroups are small, so we'll miss them unless we stratify the sample, and that starts getting complicated.

2. Bump up the MPLE to sample all possible dyads.  I'm not even sure this is possible.

If neither of these options is workable, then we're at a dead end, yes?



--

**Comment by chad-klumb** [comment]
I've updated the PR on `ergm` to take all informative dyads automatically; once you upgrade to that version you should not need to set the `control` argument anymore.

**Comment by chad-klumb** [comment]
I would also add that since `predict` adds `indices` to the formula each (informative) dyad will have its own unique type, so the number of unique dyad types we want to keep is the same as the number of informative dyads.

**Comment by martinamorris** [comment]
Thx @chad-klumb.  I'm guessing the number of indices is small when we're working with factor level covariates, and rises quickly with continuous covariates.  Downloading from your repo now, will let you know what happens.

**Comment by martinamorris** [comment]
@chad-klumb, still getting the wrong edgecount with offsets from your latest ergm commit, though the MPLE warning is gone.  but i can see now what it's doing:

```
> mixingmatrix(faux.magnolia.high, "Sex")
Note:  Marginal totals can be misleading
 for undirected mixing matrices.
    F   M
F 430 285
M 285 259
```

when you use the offset to prohibit samesex ties, sum(predicted tie) = 285.


```
> fit <- ergm(faux.magnolia.high ~ edges
+             + nodefactor("Grade")
+             + nodematch("Grade")
+             + offset(nodematch("Sex")),
+             offset.coef = (-Inf))
Starting maximum pseudolikelihood estimation (MPLE):
Evaluating the predictor and response matrix.
Maximizing the pseudolikelihood.
Finished MPLE.
Stopping at the initial estimate.
Evaluating log-likelihood at the estimate. 
> pnet <- predict(fit) # data frame
> vnet <- bind_rows(tibble(vertex.names=pnet[,1], p=pnet[,3]),
+                   tibble(vertex.names=pnet[,2], p=pnet[,3]))
> deg <- vnet %>%
+   group_by(vertex.names) %>%
+   summarize(deg = sum(p))
`summarise()` ungrouping output (override with `.groups` argument)
> egos <- ergm.ego::as.egodata(faux.magnolia.high)$egos %>%
+   mutate(vertex.names = as.numeric(vertex.names)) %>%
+   right_join(deg)
Joining, by = "vertex.names"
> sum(egos$deg)/2
[1] 285
> summary(faux.magnolia.high ~ edges)
edges 
  974 
```

So, is it deleting the forbidden dyads at the start, leaving an edgecount of 285 in the residual dyads for the model fit?  If so, this presumably would only delete observed edges if they existed in the forbidden dyads.  They do in faux.magnolia.  But they don't in my WHAMP networks -- will try those next.

**Comment by martinamorris** [comment]
on the WHAMP network:  too big

```
> pnet <- predict(fit_casl) # data frame
Error in ergm.pl(nw, fd, model, verbose = verbose, control = control,  : 
  long vectors (argument 13) are not supported in .C
```

**Comment by chad-klumb** [comment]
It exceeds a limitation of the C API used by `master`.

It may be possible to get it working with `dev`.  Other issues with exceeding 32 bit limits may also arise.

**Comment by chad-klumb** [comment]
I have made a minimal set of changes to a `dev` branch and they superficially appear to be working for a toy model.

The install stack is

```
remotes::install_github(c("statnet/rle",
                          "statnet/statnet.common",
                          "statnet/network",
                          "statnet/ergm-private@predict_dev_test",
                          "chad-klumb/ergm.ego@master"), dependencies=FALSE, force=TRUE)
```

An example usage is

```
require(ergm)

netsize <- 15000

nw <- network.initialize(netsize,dir=F)

nw <- san(nw ~ edges, target.stats=netsize)
nw %v% "attr" <- sample(letters[1:7], netsize, TRUE)

fit <- ergm(nw ~ edges + nodemix("attr", levels2=-1))

pnet <- predict(fit)
```

No control argument should be needed.

It will take a fair amount of memory and at least several minutes of runtime so I would use the Rstudio servers.

The `faux.magnolia` example should not be expected to have `predicted total # edges = observed total # edges` when the MPLE is used as the coefficient estimate for the reasons explained above; the WHAMP stuff presumably should not have the same problem.

**Comment by mbojan** [comment]
The issue is essentially about ERGMs with offset with ergm.ego-s as a special case of interest. I'm moving the issue to `ergm`.
